name = input("Enter your full name: ")
age = int(input("Enter your age: "))
student_id = input("Enter your student ID: ")
city = input("Enter your city: ")
university = input("Enter your university: ")
department = input("Enter your department: ")
email = input("Enter your email: ")
phone = input("Enter your phone number: ")
language = input("Enter your favorite programming language: ")
goal = input("Enter your programming goal: ")

print("\n================================================")
print("              AKIBA STUDENT PROFILE")
print("================================================")

print(f"Name:                 {name}")
print(f"Student ID:           {student_id}")
print(f"Age:                  {age}")
print(f"City:                 {city}")
print(f"University:           {university}")
print(f"Department:           {department}")
print(f"Email:                {email}")
print(f"Phone:                {phone}")
print(f"Favorite Language:    {language}")

print("\nProgramming Goal:")
print(goal)

print("================================================")